### ISSUE TITLE
Weekly Auto-PR via Dependabot for updating dependancies

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/open-api-framework#52]
### Thema / Theme

Other

### Omschrijving / Description

Discussed with @sergei-maertens . Most of our Maykin / Team Bron repositories make use of the dependabot alerts, however we disable the default PR-creating feature of dependabot because you get 1 PR per security update which drives everyone insane.

I'd like to try out configuring Dependabot in a smarter way, namely to auto-create on a weekly basis a single PR to update all pypi dependancies in one go. This seems possible via the groups mechanism:

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

Example 3 shows how this can be done on a weekly basis for npm:

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#example-3

This should reduce the amount of noise and help us out into autopatching of dependancies with security advisories. Maybe updates should be limited to minor+patch versions to avoid automatically taking major version upgrades into this PR.

The same could also be done for npm dependancies if applicable. Please experiment with configuring dependabot via the yml file

**Comment by sam-bertin** [comment]
Ok I had a look on how I could configure this.
Could you recommend me a repository where to test it without being annoying to the whole organization ?
I don't really wan't to try on maykin's repos cause the dependabot file needs to be commited to the default branch. 
At the same time, I would like to test on a repo that you are familiar enough so we can look at the results to see if they suit you.

**Comment by sam-bertin** [comment]
### Dependabot Configuration Report
**Configuration Overview**

The current Dependabot configuration is designed to manage dependency updates for both pip and npm ecosystems. The configuration is structured as follows:

```yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    versioning-strategy: "auto"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    groups:
      pypi-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "auto"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
```

**Observed Behavior**

Despite the configuration, Dependabot is not grouping all updates into a single pull request (PR) for each ecosystem. Instead, it is creating multiple PRs, including individual PRs for some dependencies. For example, for the npm ecosystem, the following PRs were observed:

-     Bump the npm-dependencies group with 19 updates
-     Bump @ckeditor/ckeditor5-table from 33.0.0 to 43.0.0
-     Bump microscope-sass from 1.1.0 to 2.0.0
-     Bump @ckeditor/ckeditor5-autoformat from 33.0.0 to 43.0.0
-     ... and more (total of 20 PRs regarding npm, which corresponds to the limit set in the configuration)

**Analysis**

The observed behavior can be attributed to several factors:

-     Grouping Limitations:
      Dependabot may not always be able to group all updates into a single PR due to version incompatibilities or other constraints.

-     Open Pull Requests Limit:
      The configuration limits the number of open PRs to 20. If the number of updates exceeds this limit, some updates will be handled individually.

-     Individual Updates:
      Certain updates may be critical or have specific dependencies that require them to be handled individually to minimize conflicts or compatibility issues.

**Comment by sam-bertin** [comment]
### Experimentation 

```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "auto"
    open-pull-requests-limit: 60
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
```
**Changes**
- Bumped the limit of pull requests to 60
- Limited to npm only to clarify the results

**Results**

There were 38 npm security alerts with the following severity levels 

![image](https://github.com/user-attachments/assets/5ce5ae66-db46-448e-9d67-0a55ba98eb29)

It resulted in 8 pull requests : 

![image](https://github.com/user-attachments/assets/85c5a549-1f1e-4881-9370-94d96ac4055f)

**Analysis**

- A single action was launched to handle the security alerts. (https://github.com/sam-bertin/test-dependabot/actions/runs/10403571493/job/28810321903)
- Augmenting the `open-pull-requests-limit` does not affect the limit of dependencies in the group.
- 19 + 6 = 26 dependencies adressed out of the 28.
- No idea what happened with the latest two.
- I also don't understand why I had much more PR for npm updates on the previous run.

**Comment by sam-bertin** [comment]
```yml
- package-ecosystem: "pip"
    directory: "/requirements"
    versioning-strategy: "auto"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    groups:
      pypi-dev:
        patterns:
          - "dev.txt"
        update-types:
          - "minor"
          - "patch"
      pypi-staging:
        patterns:
          - "staging.txt"
        update-types:
          - "minor"
          - "patch"
      pypi-prod:
        patterns:
          - "production.txt"
        update-types:
          - "minor"
          - "patch"
      pypi-test:
        patterns:
          - "test.txt"
        update-types:
          - "minor"
          - "patch"
      pypi-ci:
        patterns:
          - "ci.txt"
        update-types:
          - "minor"
          - "patch"
      pypi-base:
        patterns:
          - "base.txt"
        update-types:
          - "minor"
          - "patch"
 ```
 
 
 I decoupled the dependency files for python to figure out whether or not one file was causing the parsing problem.
 
 This did not help, job still fails without much detail : https://github.com/sam-bertin/test-dependabot/actions/runs/10404169142/job/28812078285
 https://github.com/sam-bertin/test-dependabot/network/updates/869836917

**Comment by sam-bertin** [comment]
### Possibly linked issue 

https://github.com/dependabot/dependabot-core/issues/8380

**Comment by sam-bertin** [comment]
@alextreme this config is giving me the best results so far : 

```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "auto"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "auto"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      pypi-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "ci.txt"  
        update-types:
          - "minor"
          - "patch"
```
---
**Results observed** 

- 2 actions launched 
![image](https://github.com/user-attachments/assets/356f6e9b-299a-4a5c-a54b-8e16312c0bb2)
- 2 Pull requests open
![image](https://github.com/user-attachments/assets/2111e964-87aa-4036-84fd-05a56fe78200)
---
I have prepared this documentation to set it up :
---
### Dependabot Configuration Documentation
**Introduction**

Dependabot is a tool that helps keep your dependencies up-to-date by automatically creating pull requests for updates. This documentation explains our Dependabot configuration, how it works, and how to set it up.

**Configuration Overview**

Our repository is set up with the following Dependabot configuration:

```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "auto"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "auto"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      pypi-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "ci.txt"
        update-types:
          - "minor"
          - "patch"
```
**What It Does for You**

- Automatic Updates: Dependabot will automatically create pull requests to update your dependencies.
- Weekly Schedule: Updates are checked and pull requests are created on a weekly basis.
- Grouped Updates: Dependencies are grouped to minimize the number of pull requests.
- Versioning Strategy: The versioning strategy is set to "auto," meaning Dependabot will use the most appropriate versioning strategy for each dependency.
- Open Pull Requests Limit: Only one pull request will be open at a time for each ecosystem to avoid overwhelming the review process.

**How to Set It Up**

- Create a .github Directory: If it doesn't already exist, create a .github directory in the root of your repository.
- Create a dependabot.yml File: Inside the .github directory, create a file named dependabot.yml.
- Add the Configuration: Copy the configuration provided above into the dependabot.yml file.
- Commit and Push: Commit the changes and push them to the repository.

**Important Notes**

- Excluding `ci.txt`: We have excluded `ci.txt` from the pip dependencies because there is no matching `ci.in` file. Ensure that both `.txt` and `.in` are present if you want them to be parsed.
- Dependabot Documentation: For more detailed information, refer to the official [Dependabot documentation](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates).

**Conclusion**

Dependabot is a powerful tool that helps keep our dependencies up-to-date with minimal manual intervention. By following the configuration and guidelines provided, we can ensure that our project remains secure and up-to-date.

If you have any questions or need further assistance, please reach out.
